/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f6fb8bb5a8424c84c66a89452bfa03c5)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  LogSession: DurableObjectNamespace<import("./src/server").LogSession>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "LogSession";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
